LAB 3: NUMPY BASICS

JOHN CYRIL DUMAGUIN

BSECE 3C

JANUARY 17, 2026

In [2]:
#%pip install numpy --upgrade
#%pip install scipy --upgrade

In [5]:
#% install --upgrade pip

In [3]:
#imports and packages
import numpy as np
from scipy import stats
from statistics import multimode

1D ARRAY

In [4]:
# 1-dimensional array
array_a = np.array([1, 2, 2, 3])
array_a

array([1, 2, 2, 3])

In [6]:
# size of an array
np.shape(array_a)

(4,)

In [7]:
# 1-dimensional array
array_b = np.array([4, 5, 6])
array_b

array([4, 5, 6])

2D ARRAY

In [8]:
# 2-dimensional array
my_array = np.array([[1, 2, 3], [4, 5, 6]])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
#size of matrix
np.shape(my_array)

(2, 3)

In [10]:
#transpose of a matrix
t_array = my_array.T
t_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [11]:
#size of matrix
np.shape(t_array)

(3, 2)

In [15]:
#jaguar vs panther 
resistance = np.array([
    [10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8],
  [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan]
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [16]:
np.shape(resistance)

(2, 11)

In [17]:
resistance.T

array([[10.6, 10.1],
       [ 9.1, 11. ],
       [ 9.3,  9.1],
       [ 9.8, 20. ],
       [10.5,  9.2],
       [10.4, 10.8],
       [ 9.5,  9.9],
       [11. ,  9.2],
       [10.4,  9.1],
       [ 3. ,  9.1],
       [ 9.8,  nan]])

In [18]:
np.mean(resistance, axis=0)

array([10.35, 10.05,  9.2 , 14.9 ,  9.85, 10.6 ,  9.7 , 10.1 ,  9.75,
        6.05,   nan])

In [19]:
np.mean(resistance, axis=1)

array([9.4, nan])

In [20]:
#mean
np.nanmean(resistance, axis=1)

array([ 9.4 , 10.75])

In [21]:
jaguar_mean=np.nanmean(resistance, axis=1)[0]
panther_mean=np.nanmean(resistance, axis=1)[1]

print(f'Jaguar Mean: {jaguar_mean: .2f} ohms')
print(f'Panther Mean: {panther_mean: .2f} ohms')

Jaguar Mean:  9.40 ohms
Panther Mean:  10.75 ohms


In [22]:
#median
np.nanmedian(resistance, axis=1)    

array([9.8 , 9.55])

In [23]:
jag_median = np.nanmedian(resistance, axis=1)[0]
pan_median = np.nanmedian(resistance, axis=1)[1]

print(f'Jaguar Median: {jag_median: .2f} ohms')
print(f'Panther Median: {pan_median: .2f} ohms')

Jaguar Median:  9.80 ohms
Panther Median:  9.55 ohms


In [24]:
#mode
stats.mode(resistance, axis=1)

ModeResult(mode=array([9.8, 9.1]), count=array([2, 3]))

In [25]:
my_array = [1, 1, 2, 2, 3, 4, 5]
multimode(my_array)

[1, 2]

In [26]:
jag_res = resistance[0]

print("jaguar mode")
for i in multimode(jag_res):
    print(f'{i} ohms')

jaguar mode
9.8 ohms
10.4 ohms


In [27]:
pan_res = resistance[1]

print("panther mode")
for i in multimode(pan_res):
    print(f'{i} ohms')

panther mode
9.1 ohms


MEASURES OF VARIABILITY

In [30]:
#jaguar vs panther
resistance = np.array([[10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8],[10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan]])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [31]:
#range
res_max = np.nanmax(resistance, axis=1)
res_min = np.nanmin(resistance, axis=1)

res_range = res_max - res_min
res_range

array([ 8. , 10.9])

In [32]:
print(f'Jaguar Range: {res_range[0]: .2f} ohms')
print(f'Panther Range: {res_range[1]: .2f} ohms')

Jaguar Range:  8.00 ohms
Panther Range:  10.90 ohms


In [33]:
#1st quartile
res_Q1 = np.nanpercentile(resistance, 25, axis=1)
res_Q1

array([9.4  , 9.125])

In [34]:
#2nd quartile
res_Q2 = np.nanpercentile(resistance, 50, axis=1)
res_Q2

array([9.8 , 9.55])

In [35]:
#3rd quartile
res_Q3 = np.nanpercentile(resistance, 75, axis=1)
res_Q3

array([10.45 , 10.625])

In [36]:
#IQR
print(f'Jaguar IQR: {res_Q3[0] - res_Q1[0]: .2f} ohms')
print(f'Panther IQR: {res_Q3[1] - res_Q1[1]: .2f} ohms')

Jaguar IQR:  1.05 ohms
Panther IQR:  1.50 ohms


In [37]:
#variance
res_variance = np.nanvar(resistance,ddof=1, axis=1)
res_variance

array([ 4.86      , 11.08277778])

In [38]:
print(f'Jaguar Variance: {res_variance[0]: .2f} ohms')
print(f'Panther Variance: {res_variance[1]: .2f} ohms')

Jaguar Variance:  4.86 ohms
Panther Variance:  11.08 ohms


In [39]:
#standard deviation
res_std = np.nanstd(resistance,ddof=1, axis=1)
res_std

array([2.20454077, 3.32908062])

In [40]:
print(f'Jaguar Standard Deviation: {res_std[0]: .2f} ohms')
print(f'Panther Standard Deviation: {res_std[1]: .2f} ohms')

Jaguar Standard Deviation:  2.20 ohms
Panther Standard Deviation:  3.33 ohms
